### PR TITLE
CCM-31 Fix voor Unique validator

### PR DESCRIPTION
**Pull request by wpdebruin**
Fix voor Unique validator. There still is a dependency problem on cborm,
this module is officially not dependent on cborm

### CODE REVIEW

**Comment by lmajano** [comment]
Hi @wpdebruin thanks so much for this. However, I am not sure if we should add the ORM dependency in.  Basically, if we do we set a precendent for adding other module validators.  Maybe we just need to use the `validator` approach instead.  Thoughts? @bdw429s

**Comment by wpdebruin** [comment]
Hi @lmajano @bdw429s I think the validator : "UniqueValidator@cborm" approach is much cleaner. Just a ready to use validator instead of the unique validator. I just tested it and it is working fine, so 10 search and replaces and everything would be fine in our case. 
But just mention it in the docs, and most important: make sure the 'unique' syntax fails!
(btw, we already patched the cbvalidation routines for other (i18n) requirements, see my other tickets.

**Comment by wpdebruin** [comment]
Not that my vote is veryimportant, but I would definitely vote for completely removing the unique validator. Even in CB 3.8 as a plugin it was unreliable, or at least not well documented. You can validate on an object, on a set of predefined constraints (from settings) or a la carte (dynamic) constraints (whipping up a struct based on your current state). Unique ONLY works for objects, not for the other 2 situations, which is confusing. A custom validator is much clearer, in this case it is just a ready to use Custom Validator (which is fine!) As suggested by Louis, you don't need any modifications in cbvalidation, only in your constraint definitions, which is quite easy.
Just make sure there are enough warning signs for people migrating cb 3.8->4, and do not ignore, but throw an error (which would require a small code change)

**Comment by lmajano** [comment]
Sounds good then. I will update the docs to point out the integration and make the `unique` fail with message.

**Pull request closed without merging**
